language: python
python:
        - "2.7"
env:
        - TOXENV=py27
        - TOXENV=py32
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=pypy
        - TOXENV=coverage
        - TOXENV=flake8
install:
        - travis_retry pip install tox
script: tox -e $TOXENV
